plugins {
    id 'com.android.application'
}

android {
    namespace 'com.rickyid666.bililivelike'
    compileSdk 34

    defaultConfig {
        applicationId "com.rickyid666.bililivelike"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        debug {
            applicationIdSuffix ""
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packagingOptions {
        resources.excludes += ["META-INF/*"]
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

// 调试包直接可用 (debug 签名), 无需配置 keystore
